name: Roman Komkov
bio: 'Creating and maintaining modern solid infrastructures'
picture: 'assets/images/profile.jpg'
cv: 'assets/documents/cv_roman_komkov.docx'

url: http://komkov.co
# url: http://localhost:3000

# if it's an external image, update below for true
external-image: false

permalink: /:title/

markdown: kramdown
highlighter: rouge

analytics-google: 'UA-76143048-1'

# To enable piwik tracking, supply your url & site ID below
# analytics-piwik-url: 'piwik.my-host.com'
# analytics-piwik-id: 1

# if you don't have any of social below, comment the line
disqus: komkov
twitter: alkoengineering
linkedin: rkomkov
github: decayofmind
email: roman@komkov.co

# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# if you don't need pagination, comment the *paginate* configs below
# paginate: 5
# paginate_path: "blog/:num/"

projects: false
about: true
blog: true

# do you want to show the "read time" of the posts?
read-time: true

# do you want to show the "tags" inside the posts?
show-tags: true

# related posts inside a post?
related: true

# do you want some animations?
animation: true

gems:
  - jemoji
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-paginate

jekyll-mentions:
    base_url: https://github.com

exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, indigo-gh-pages.zip, Rakefile, screen-shot.png, travis.sh]
